version: "3.8"

services:
    longevity:
        build: .
        container_name: longevity
        command: > 
            sh -c "python manage.py makemigrations user &&
                   python manage.py migrate &&
                   python manage.py create_super_user &&
                   python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app
        ports: 
            - "8000:8000"
        depends_on:
            - longevity_db
    longevity_db:
        image: postgres
        container_name: longevity_db
        environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        expose:
          - '5432'
        ports:
          - '5106:5432'
