version: "3.8"

services:
    longevity:
        build: .
        container_name: longevity
        command: > 
            sh -c "python manage.py makemigrations &&
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app
        ports: 
            - "8000:8000"
        depends_on:
            - longevity_db
            - longevity_redis
    longevity_db:
        image: postgres
        container_name: longevity_db
        environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        expose:
          - '5432'
        ports:
          - '5105:5432'
    longevity_redis:
        image: redis
        container_name: longevity_redis
        ports:
        - "6379"
        restart: always
    celery:
        build: .
        command: celery -A longevity worker -l INFO
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://longevity_redis:6379/0
            - CELERY_BACKEND=redis://longevity_redis:6379/0
        depends_on:
            - longevity
            - longevity_redis